#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
VISUAL_ENV_FILE="/etc/sandboxmcp/visual.env"
SYSTEMD_DIR="${REPO_ROOT}/systemd"
DISPLAY_DEFAULT=":1"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  source "${ENV_FILE}"
  set +a
fi

ENABLE_VISUAL_RAW="${ENABLE_VISUAL:-auto}"
ENABLE_VISUAL="${ENABLE_VISUAL_RAW,,}"
DISPLAY_NUM="${DISPLAY_NUM:-${DISPLAY_DEFAULT}}"
DISPLAY_ID="${DISPLAY_NUM#:}"
if [[ -z "${DISPLAY_ID}" ]]; then
  DISPLAY_ID="1"
fi
if [[ "${DISPLAY_NUM}" != :* ]]; then
  DISPLAY_NUM=":${DISPLAY_ID}"
fi
NOVNC_LISTEN="${NOVNC_LISTEN:-127.0.0.1}"
NOVNC_PORT="${NOVNC_PORT:-6080}"
VNC_PORT="${VNC_PORT:-5901}"
QT_OPENGL="${QT_OPENGL:-software}"
LIBGL_ALWAYS_SOFTWARE="${LIBGL_ALWAYS_SOFTWARE:-1}"
CHROMIUM_FLAGS="${CHROMIUM_FLAGS:---disable-gpu --no-sandbox --disable-dev-shm-usage}"

PACKAGES=(
  xorg
  xvfb
  openbox
  x11vnc
  novnc
  websockify
  x11-xserver-utils
  dbus-x11
  fonts-dejavu-core
  fonts-liberation
  fonts-noto-core
  firefox-esr
  mesa-utils
  libgl1-mesa-dri
)

SERVICES=(
  xvfb@${DISPLAY_ID}.service
  openbox@${DISPLAY_ID}.service
  x11vnc@${DISPLAY_ID}.service
  novnc@${DISPLAY_ID}.service
)

log() {
  echo "[visual] $*"
}

require_root() {
  if [[ ${EUID} -ne 0 ]]; then
    log "This action requires root privileges." >&2
    exit 1
  fi
}

visual_disabled() {
  if [[ "${ENABLE_VISUAL}" == "false" ]]; then
    log "ENABLE_VISUAL=false — визуальное окружение отключено. Обновите .env при необходимости."
    return 0
  fi
  return 1
}

display_running() {
  local id="$1"
  if pgrep -f "Xvfb :${id}" >/dev/null 2>&1; then
    return 0
  fi
  if command -v xdpyinfo >/dev/null 2>&1; then
    if DISPLAY=":${id}" xdpyinfo >/dev/null 2>&1; then
      return 0
    fi
  fi
  return 1
}

install_packages() {
  require_root
  local missing=()
  for pkg in "${PACKAGES[@]}"; do
    if ! dpkg -s "${pkg}" >/dev/null 2>&1; then
      missing+=("${pkg}")
    fi
  done

  if (( ${#missing[@]} > 0 )); then
    log "Installing packages: ${missing[*]}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends "${missing[@]}"
  else
    log "Visual packages already installed."
  fi

  ensure_chromium
  ensure_telegram
}

ensure_chromium() {
  if command -v chromium >/dev/null 2>&1 || command -v chromium-browser >/dev/null 2>&1; then
    return
  fi

  if apt-get install -y --no-install-recommends chromium >/dev/null 2>&1; then
    log "Chromium installed via apt."
    return
  fi

  if command -v snap >/dev/null 2>&1; then
    log "Installing Chromium via snap (fallback)..."
    snap install chromium --classic || log "Failed to install Chromium via snap; install manually."
  else
    log "Chromium package not available and snap missing; install manually if требуется."
  fi
}

ensure_telegram() {
  if command -v telegram-desktop >/dev/null 2>&1; then
    return
  fi

  if apt-get install -y --no-install-recommends telegram-desktop >/dev/null 2>&1; then
    log "Telegram Desktop installed via apt."
    return
  fi

  if command -v snap >/dev/null 2>&1; then
    log "Installing Telegram Desktop via snap (fallback)..."
    snap install telegram-desktop || log "Failed to install Telegram Desktop via snap; install manually."
  else
    log "Telegram Desktop package not available and snap missing; install manually."
  fi
}

write_visual_env() {
  require_root
  mkdir -p /etc/sandboxmcp
  {
    printf '# Generated by install-visual.sh\n'
    printf 'DISPLAY_NUM=%q\n' "${DISPLAY_NUM}"
    printf 'DISPLAY_ID=%q\n' "${DISPLAY_ID}"
    printf 'NOVNC_LISTEN=%q\n' "${NOVNC_LISTEN}"
    printf 'NOVNC_PORT=%q\n' "${NOVNC_PORT}"
    printf 'VNC_PORT=%q\n' "${VNC_PORT}"
    printf 'QT_OPENGL=%q\n' "${QT_OPENGL}"
    printf 'LIBGL_ALWAYS_SOFTWARE=%q\n' "${LIBGL_ALWAYS_SOFTWARE}"
    printf 'CHROMIUM_FLAGS=%q\n' "${CHROMIUM_FLAGS}"
  } > "${VISUAL_ENV_FILE}"
  chmod 0644 "${VISUAL_ENV_FILE}"
}

install_unit() {
  local unit="$1"
  local source="${SYSTEMD_DIR}/${unit}"
  local target="/etc/systemd/system/${unit}"

  if [[ ! -f "${source}" ]]; then
    log "Unit template ${unit} not found in repository." >&2
    exit 1
  fi

  if [[ -f "${target}" ]]; then
    if cmp -s "${source}" "${target}"; then
      return
    fi
  fi

  install -m 0644 "${source}" "${target}"
}

install_units() {
  require_root
  for unit in xvfb@.service openbox@.service x11vnc@.service novnc@.service; do
    install_unit "${unit}"
  done
  systemctl daemon-reload
}

start_units() {
  require_root
  local srv
  for srv in "${SERVICES[@]}"; do
    systemctl enable --now "${srv}"
  done
}

stop_units() {
  require_root
  local srv
  for srv in "${SERVICES[@]}"; do
    if systemctl list-unit-files | grep -q "^${srv}"; then
      systemctl disable --now "${srv}" || true
    else
      systemctl disable --now "${srv}" 2>/dev/null || true
    fi
  done
}

status_units() {
  local srv
  for srv in "${SERVICES[@]}"; do
    if systemctl list-unit-files "${srv}" >/dev/null 2>&1; then
      local state
      state=$(systemctl is-active "${srv}" 2>/dev/null || echo "inactive")
      echo "${srv}: ${state}"
    else
      echo "${srv}: not installed"
    fi
  done
}

usage() {
  cat <<'USAGE'
Usage: install-visual.sh <command>

Commands:
  packages    Install visual environment packages (idempotent)
  enable      Install unit files, write env and start services
  disable     Stop and disable visual services
  status      Show status of visual services
USAGE
}

should_skip_enable() {
  if [[ "${ENABLE_VISUAL}" == "auto" ]]; then
    if display_running "${DISPLAY_ID}"; then
      log "Display :${DISPLAY_ID} already active — skipping enable."
      return 0
    fi
  fi
  return 1
}

ACTION="${1:-help}"

case "${ACTION}" in
  packages)
    if visual_disabled; then exit 0; fi
    install_packages
    ;;
  enable)
    if visual_disabled; then exit 0; fi
    install_packages
    write_visual_env
    install_units
    if ! should_skip_enable; then
      start_units
      log "Visual services started on DISPLAY=${DISPLAY_NUM}."
    fi
    ;;
  disable)
    stop_units
    ;;
  status)
    status_units
    ;;
  *)
    usage
    exit 1
    ;;
 esac
